<?php

function update8_3() {
	pad_update_option( 'onlybookingelparticulier', '0' );
	pad_update_option( 'cancelbookingafternopayment', '0' );
	pad_update_option( 'bedanktredirect', '1' );
	pad_update_option( 'bedankurl', '0' );
	pad_update_option( 'bedankttekst',
		'Hallo {naam}, Bedankt voor je aanmelding voor de cursus: {cursus} met startdatum: {startdatum}. Zodra wij deze hebben verwerkt krijg je nog een definitieve bevestiging per E-mail.' );
	pad_update_option( 'bedanktredirectmislukt', '1' );
	pad_update_option( 'bedankurlmislukt', '0' );
	pad_update_option( 'bedankttekstmislukt',
		'Hallo {naam}, Bedankt voor je aanmelding voor de cursus: {cursus} met startdatum: {startdatum}. Om een of andere reden is de boeking niet gelukt. Neem voor de zekerheid contact met ons op zodat wij dit kunnen nakijken.' );
	pad_update_option( 'mailcursusaanmelding', '' );
	pad_update_option( 'dagdelentekst', 'Dagdelen' );
	pad_update_option( 'toonomschrijvingcursus', '1' );
	pad_update_option( 'toondebuginfo', '0' );
	pad_update_option( 'betalingenactief', '0' );
	pad_update_option( 'optiesmeetellen', '1' );
	pad_update_option( 'btwinofexbtwtonen', '1' );
	pad_update_option( 'btwinofexbtwtonenlabel', '0' );
	pad_update_option( 'skipcoursewithonlyelearning', '1' );
	pad_update_option( 'toonimginoverzicht', '0' );
	pad_update_option( 'limiettekstomschrijving', '' );
	pad_update_option( 'tekstgeencursussen', 'Momenteel zijn er geen cursussen gevonden, bel naar ons voor meer informatie. Of vul dit' );
	pad_update_option( 'buttontekstoverzicht', '' );
	pad_update_option( 'tooncode95overzicht', '0' );
	pad_update_option( 'toonsooboverzicht', '0' );
	pad_update_option( 'toonelearningdagdeelinoverzicht', '0' );
	pad_update_option( 'toondetaildagdelenlijstinoverzicht', '0' );
	pad_update_option( 'toonlocatiedagdeeloverzicht', '0' );
	pad_update_option( 'toonlabelindagdeel', '0' );
	pad_update_option( 'tooncostsremarkoverzicht', '0' );
	pad_update_option( 'tooncursuselearning', '0' );
	pad_update_option( 'tooncursuslabelsoverzicht', '0' );
	pad_update_option( 'toondagdelen', '0' );
	pad_update_option( 'toonlocatiebijoverzicht', '0' );
	pad_update_option( 'toonprijs', '0' );
	pad_update_option( 'toonvollecursus', '0' );
	pad_update_option( 'tooncursusdagdelenverleden', '0' );
	pad_update_option( 'toonbutton', '1' );
	pad_update_option( 'startgarantieoverzicht', '0' );
	pad_update_option( 'geldterugoverzicht', '0' );
	pad_update_option( 'toonimginoverzicht', '0' );
	pad_update_option( 'limiettekstomschrijving', '200' );
	pad_update_option( 'tekstgeencursussen', 'Momenteel zijn er geen cursussen gevonden, bel naar ons voor meer informatie. Of vul dit' );
	pad_update_option( 'buttontekstoverzicht', 'Bekijk cursus' );
	pad_update_option( 'toonsoobdetailcursus', '0' );
	pad_update_option( 'tooncode95cursus', '0' );
	pad_update_option( 'tooncursuslabelsdetail', '0' );
	pad_update_option( 'toondetaildagdelen', '1' );
	pad_update_option( 'toondetaildagdelenlijst', '0' );
	pad_update_option( 'toonlocatiedagdeel', '1' );
	pad_update_option( 'toonelearningdagdeel', '0' );
	pad_update_option( 'toonniveau', '0' );
	pad_update_option( 'toonomschrijvingdagdeel', '0' );
	pad_update_option( 'toonbeschikbareplaatsen', '0' );
	pad_update_option( 'startgarantiedetail', '0' );
	pad_update_option( 'geldterugdetail', '0' );
	pad_update_option( 'tooncostsremark', '0' );
	pad_update_option( 'toonprijsdetailpagina', '1' );
	pad_update_option( 'countelearningasdaypart', '0' );
	pad_update_option( 'toonimgindetail', '0' );
	pad_update_option( 'calendarcolorback', '' );
	pad_update_option( 'calendarcolortext', '' );
	pad_update_option( 'tooncalendarmouseover', '1' );
	pad_update_option( 'materialbookingactive', '0' );
	pad_update_option( 'materialtitle', 'Welke opties zou je willen meebestellen?' );
	pad_update_option( 'materialtext', '' );
	pad_update_option( 'toontextbijsearch', '1' );
	pad_update_option( 'toonlocatiesbijsearch', '0' );
	pad_update_option( 'toonlabelsbijsearch', '0' );
	pad_update_option( 'tooncode95bijsearch', '0' );
	pad_update_option( 'toonsoobbijsearch', '0' );
	pad_update_option( 'toonelearningbijsearch', '0' );
	pad_update_option( 'tooninblockvorm', '1' );
	pad_update_option( 'mailcursusaanmeldingcursist', '0' );
	pad_update_option( 'mailbedankttekst',
		'Hallo {naam}, Er is een aanmelding binnengekomen voor de cursus: {cursus} met startdatum: {startdatum}. Deze aanmelding voor de cursus/opleiding is bij ons binnengekomen en moet nog worden verwerkt. Zodra wij deze hebben verwerkt krijg je nog een definitieve bevestiging per E-mail. Met vriendelijke groet, -- {website}' );
	pad_update_option( 'mailcursusaanmeldingbedrijf', '0' );
	pad_update_option( 'mailbedankttekstbedrijf', '' );
	pad_update_option( 'onlybookingelparticulier', '0' );
	pad_update_option( 'voorkeurbooleancompany', '1' );
	pad_update_option( 'vraagadrescursist', '0' );
	pad_update_option( 'vraaghuisnrext', '0' );
	pad_update_option( 'vraagcontactpersoon', '0' );
	pad_update_option( 'vraagroepnaam', '0' );
	pad_update_option( 'vraagmeisjesnaam', '0' );
	pad_update_option( 'vraag_internal_reference', '0' );
	pad_update_option( 'vraagcostcentercode', '0' );
	pad_update_option( 'vraagcostcentercodemanatory', '0' );
	pad_update_option( 'tekstkostenplaats', 'Kostenplaats' );
	pad_update_option( 'vraagpersoneelsnummer', '0' );
	pad_update_option( 'toonformdateofbirth', '0' );
	pad_update_option( 'toonformdateofbirthmanatory', '0' );
	pad_update_option( 'toonformcountryofbirth', '0' );
	pad_update_option( 'toonformcountryofbirthmanatory', '0' );
	pad_update_option( 'toonemailinvoice', '0' );
	pad_update_option( 'toonemailinvoicemanatory', '0' );
	pad_update_option( 'toonformphonenumbermanatory', '0' );
	pad_update_option( 'toonformphonenumbercompany', '0' );
	pad_update_option( 'toonformphonenumbercompanymanatory', '0' );
	pad_update_option( 'toonformpositionstudent', '0' );
	pad_update_option( 'toonformpositionstudentmanatory', '0' );
	pad_update_option( 'toonoptiecode95', '0' );
	pad_update_option( 'tekstcode95optie', 'Cursus bevat code95, deze deelnemer ook meteen hiervoor aanmelden?' );
	pad_update_option( 'toonoptiesoob', '0' );
	pad_update_option( 'tekstsooboptie', 'Cursus bevat SOOB, deze deelnemer ook meteen hiervoor aanmelden?' );
	pad_update_option( 'toonstudentremark', '0' );
	pad_update_option( 'teksttitelbooking', 'Cursus boeken en meteen zelf boeken' );
	pad_update_option( 'toonformalgemenevoorwaarden', '0' );
	pad_update_option( 'urlalgemenevoorwaarden', '' );
	pad_update_option( 'toonapiattributen', '0' );
	pad_update_option( 'vraagfinancieleinfobijbedrijf', '0' );
	pad_update_option( 'dbcoursehours', '12' );
	pad_update_option( 'dbdaypartshours', '24' );

	update_option( 'planaday-api-version', '8.3' );
}